ast/antlrhandler: add hints to syntax errors (#2667)
Our parser/lexer syntax errors are extremely hard to comprehend and have
been causing confusion. This updates our ErrorListener and ErrorStrategy
with a few niceties, attempting to add extra context about the incorrect
syntax.

These cases are pretty minimal, but they're a start.

---

For issue #2656 in particular, here's the updated error message:

```
Error: build target: build main: failed to solve: resolve build context for target +foo: Earthfile line 5:45 '
': invalid syntax

Hints:
  - I got lost looking for '=' - did you define a key/value pair without a value?
```