Don't pass --platform to docker/podman (#2511)
The `--platform` flag is only ever passed to docker/podman when both the
user and server platform values are equal. When they mismatch, the
`--platform` flag is ommitted, and the server's native platform is used.

Since the `--platform` value is only ever passed when the user and
server platforms are equal, it shouldn't matter; however in practice
there is a podman bug, which causes a pull to occur whenver the
`--platform` flag is specified:
https://github.com/containers/podman/issues/15711

This bug will cause podman to always pull the earthly/buildkitd image
from docker hub, which will either 1) overwrite the local image if the image
exists in docker hub, and ultimately will cause our tests to run against an 
incorrect image version, or 2) result in the following 404-error if the tag
does not exist:

    exit status 125: Trying to pull docker.io/earthly/buildkitd:dev-HEAD...
    Error: initializing source docker://earthly/buildkitd:dev-HEAD: reading
    manifest dev-HEAD in docker.io/earthly/buildkitd: manifest unknown:
    manifest unknown: exit status 125

This additionally updates the podman tests to use capsh rather
than grep for the `RUN --privileged` tests, as the Effective
capabilities (CapEff) bits are not always the same between docker 
and podman

Signed-off-by: Alex Couture-Beil <alex@earthly.dev>