Improve error reporting in satellite auth (#2967)
Some context was missing in a recent auth error reported by satellite
users.

The error reported by the user was:
```
Error: could not construct new buildkit client: unable to authenticate
```

The additional context added here should help both us and the user debug
similar auth issues.