Requires FROM error message improvement and errors in source link format (#4073)
Old Error:
```
Error: tests/raw-output2/Earthfile Line:7:4 the first command has to be FROM, FROM DOCKERFILE, LOCALLY, ARG, BUILD or IMPORT
```
New Error:
```
Error: tests/raw-output2/Earthfile:7:4 apply FOR ... IN: requires a FROM, FROM DOCKERFILE, or LOCALLY

  Hint: This command needs to run in a shell. You should be able to solve this by adding 'FROM someImage' on the line before this one.

in              github.com/earthly/earthly/tests/raw-output2:agbell/error_message+for
```

### Error to Source link format

The `path:line:col` is source link format that is clickable in VS Code,
intellij and other IDEs. Changing errors to use it instead of `Error:
file Line:line:col`