Display which secret was not found in error message (#972)
Previously if one referenced a secret which was not available, earthly
would fail and simply return "Error: not found"; this changes the
behavious to display which secret was not found.

For example, consider an Earthfile like:

    foo:
        FROM alpine:latest
        RUN --secret password=+secrets/password env

If you invoke earthly +foo (without passing a value for the password secret), now it will display
an error such as:

    Error: unable to lookup secret password: not found

Where as previously it just displayed:

    Error: not found

Signed-off-by: Alex Couture-Beil <alex@earthly.dev>