warn if file-lock takes more than 3 seconds (#3092)
If the file-lock blocks for more than 3 seconds, display a warning:

    waiting on lock "/home/alex/.earthly-dev/buildkitd-startup.lock"

to give the user some feedback; otherwise, the user will have to wait 5
minutes until getting stack-trace error:

    Error stack trace:
    github.com/earthly/earthly/buildkitd.maybeStart
    	/earthly/buildkitd/buildkitd.go:181
    github.com/earthly/earthly/buildkitd.NewClient
    	/earthly/buildkitd/buildkitd.go:111
    main.(*earthlyApp).actionBuildImp
    	/earthly/cmd/earthly/build_cmd.go:301
    main.(*earthlyApp).actionBuild
    	/earthly/cmd/earthly/build_cmd.go:86
    github.com/urfave/cli/v2.(*App).RunContext
    	/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322
    main.(*earthlyApp).run
    	/earthly/cmd/earthly/main.go:716
    main.main
    	/earthly/cmd/earthly/main.go:323
    runtime.main
    	/usr/local/go/src/runtime/proc.go:250
    runtime.goexit
    	/usr/local/go/src/runtime/asm_amd64.s:1598
Error: build new buildkitd client: maybe start buildkitd: timeout
waiting for other process to start buildkitd

Which doesn't indicate the path to the lock for cases where the lock
file exists (but earthly is no longer running, e.g. is in a stopped
state).

Signed-off-by: Alex Couture-Beil <alex@earthly.dev>